#ifndef NCPU32K_MSR_H
#define NCPU32K_MSR_H

#define MAX_MSR_BANK_BITS 10 /* 1<<MAX_MSR_BANK_BITS = 65536 */

#define MSR_BANK_PSR (0 << MAX_MSR_BANK_BITS)
#define MSR_BANK_IMR (1L << MAX_MSR_BANK_BITS)
#define MSR_BANK_DMR (2L << MAX_MSR_BANK_BITS)
#define MSR_BANK_ICR (3L << MAX_MSR_BANK_BITS)
#define MSR_BANK_DCR (4L << MAX_MSR_BANK_BITS)
#define MSR_BANK_DBGR (5L << MAX_MSR_BANK_BITS)

#define MSR_DBGR_NUMPORT (MSR_BANK_DBGR + 0x0)
#define MSR_DBGR_MSGPORT (MSR_BANK_DBGR + 0x1)

#endif /* NCPU32K_MSR_H */